modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/gatekeep06/neuromon/issues"
license = "MPL-2.0"

[[mods]]
modId = "neuromon"
version = "${version}"
displayName = "Neuromon"
authors = "gatekeep06"
description = '''
A Cobblemon side mod that adds fakemon based on Neuro-sama and Evil Neuro, as well as related characters and V-Tubers.
'''
logoFile = "assets/neuromon/icon.png"

[[dependencies.neuromon]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neuromon]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neuromon]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "neuromon.mixins.json"
